name: 'CI: Nix build'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      nix: ${{ steps.filter.outputs.nix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            nix:
              - 'flake.nix'
              - 'flake.lock'
              - 'nix/**'
              - '.github/workflows/nix-build.yaml'
              - '.github/actions/setup-nix/**'

  build-linux-x86_64:
    needs: changes
    if: needs.changes.outputs.nix == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-nix
      - name: Build Linux (x86_64) Home Manager configuration
        run: |
          nix build .#homeConfigurations.mizokami.activationPackage \
            --print-build-logs \
            --show-trace

  build-linux-aarch64:
    needs: changes
    if: needs.changes.outputs.nix == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-nix
      - name: Build Linux (aarch64) Home Manager configuration
        run: |
          nix build .#homeConfigurations.mizokami-aarch64.activationPackage \
            --print-build-logs \
            --show-trace
